apiVersion: v1
kind: Pod
metadata:
  name: supermario-pod
  labels:
    app: supermario
spec:
  containers:
  - name: supermario-container
    image: pengbai/docker-supermario
    ports:
      - containerPort: 8080
    volumeMounts:
    - name: log-volume
      mountPath: /usr/local/tomcat/logs
  - name: busybox-logger
    image: busybox
    command: ['sh', '-c', 'while true; do tail -f /usr/local/tomcat/logs/catalina.*.log; done']
    volumeMounts:
    - name: log-volume
      mountPath: /usr/local/tomcat/logs
  volumes:
  - name: log-volume
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: supermario-service
spec:
  type: NodePort
  selector:
    app: supermario
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30860
